image: docker:latest

services:
  - docker:dind

before_script:
  - echo ${DOCKER_PASSWORD} | docker login registry.jakepeterson.dev --username ${DOCKER_USER} --password-stdin

# build-posts:
#   stage: build
#   script: 
#     - cd ./posts
#     - docker build -t registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-posts:latest .
#     - docker push registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-posts:latest

# build-comments:
#   stage: build
#   script: 
#     - cd ./comments
#     - docker build -t registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-comments:latest .
#     - docker push registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-comments:latest

# build-eventbus:
#   stage: build
#   script: 
#     - cd ./event-bus
#     - docker build -t registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-eventbus:latest .
#     - docker push registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-eventbus:latest

# build-frontend:
#   stage: build
#   script: 
#     - cd ./frontend
#     - docker build -t registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-frontend:latest .
#     - docker push registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-frontend:latest

# build-moderation:
#   stage: build
#   script: 
#     - cd ./moderation
#     - docker build -t registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-moderation:latest .
#     - docker push registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-moderation:latest

# build-query:
#   stage: build
#   script: 
#     - cd ./query
#     - docker build -t registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-query:latest .
#     - docker push registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-query:latest

deploy:
  stage: deploy
  script: 
    - cd ./infrastructure/k8s
    # - microk8s kubectl apply -f posts-depl.yaml -n mms-blog
    # - microk8s kubectl rollout restart deployment posts-depl -n mms-blog
    # - microk8s kubectl apply -f event-bus-depl.yaml -n mms-blog
    # - microk8s kubectl rollout restart deployment event-bus-depl -n mms-blog
    # - microk8s kubectl apply -f comments-depl.yaml -n mms-blog
    # - microk8s kubectl rollout restart deployment comments-depl -n mms-blog
    # - microk8s kubectl apply -f moderation-depl.yaml -n mms-blog
    # - microk8s kubectl rollout restart deployment moderation-depl -n mms-blog
    # - microk8s kubectl apply -f query-depl.yaml -n mms-blog
    # - microk8s kubectl rollout restart deployment query-depl -n mms-blog
    - microk8s kubectl apply -f frontend-depl.yaml -n mms-blog
    - microk8s kubectl rollout restart deployment frontend-depl -n mms-blog


