image: docker:latest

services:
  - docker:dind

before_script:
  - echo ${DOCKER_PASSWORD} | docker login registry.jakepeterson.dev --username ${DOCKER_USER} --password-stdin

build-posts:
  stage: build
  script: 
    - cd ./posts
    - docker build -t registry.jakepeterson.dev/jpeterson/ms-posts:latest .
    - docker push registry.jakepeterson.dev/jpeterson/ms-posts:latest

build-comments:
  stage: build
  script: 
    - cd ./comments
    - docker build -t registry.jakepeterson.dev/jpeterson/ms-comments:latest .
    - docker push registry.jakepeterson.dev/jpeterson/ms-comments:latest

build-eventbus:
  stage: build
  script: 
    - cd ./event-bus
    - docker build -t registry.jakepeterson.dev/jpeterson/ms-eventbus:latest .
    - docker push registry.jakepeterson.dev/jpeterson/ms-eventbus:latest

build-frontend:
  stage: build
  script: 
    - cd ./frontend
    - docker build -t registry.jakepeterson.dev/jpeterson/ms-frontend:latest .
    - docker push registry.jakepeterson.dev/jpeterson/ms-frontend:latest

build-moderation:
  stage: build
  script: 
    - cd ./moderation
    - docker build -t registry.jakepeterson.dev/jpeterson/ms-moderation:latest .
    - docker push registry.jakepeterson.dev/jpeterson/ms-moderation:latest

build-query:
  stage: build
  script: 
    - cd ./query
    - docker build -t registry.jakepeterson.dev/jpeterson/ms-query:latest .
    - docker push registry.jakepeterson.dev/jpeterson/ms-query:latest


