apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
  namespace: mms-blog
spec:
  replicas: 1
  # Tells the deployment which pods to manage by looking for pods with this label
  selector:
    matchLabels:
      app: comments
  template:
    # Assigns the label to pods this deployment creates
    metadata:
      labels:
        app: comments
    spec:
      containers: 
        - name: comments
          image: registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-comments:latest
      imagePullSecrets:
        - name: privreg
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
  namespace: mms-blog
spec:
  type: ClusterIP
  # Tells the service which label to match with service
  selector:
    app: comments
  ports: 
    - name: comments
      protocol: TCP
      # port service is listening on, could be different
      port: 4001
      # the port that the application is listening on, i.e Express Server listening on 4000
      targetPort: 4001