apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  # Tells the deployment which pods to manage by looking for pods with this label
  selector:
    matchLabels:
      app: event-bus
  template:
    # Assigns the label to pods this deployment creates
    metadata:
      labels:
        app: event-bus
    spec:
      containers: 
        - name: event-bus
          image: registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-eventbus:latest
      imagePullSecrets:
        - name: privreg
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  type: ClusterIP
  # Tells the service which label to match with service
  selector:
    app: event-bus
  ports: 
    - name: posts
      protocol: TCP
      # port service is listening on, could be different
      port: 4005
      # the port that the application is listening on, i.e Express Server listening on 4000
      targetPort: 4005