apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 1
  # Tells the deployment which pods to manage by looking for pods with this label
  selector:
    matchLabels:
      app: frontend
  template:
    # Assigns the label to pods this deployment creates
    metadata:
      labels:
        app: frontend
    spec:
      containers: 
        - name: frontend
          image: registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-frontend:latest
      imagePullSecrets:
        - name: privreg
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-srv
spec:
  type: ClusterIP
  # Tells the service which label to match with service
  selector:
    app: frontend
  ports: 
    - name: frontend
      protocol: TCP
      # port service is listening on, could be different
      port: 3000
      # the port that the application is listening on, i.e Express Server listening on 4000
      targetPort: 3000