apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
  namespace: mms-blog
spec:
  replicas: 1
  # Tells the deployment which pods to manage by looking for pods with this label
  selector:
    matchLabels:
      app: posts
  template:
    # Assigns the label to pods this deployment creates
    metadata:
      labels:
        app: posts
    spec:
      containers: 
        - name: posts
          image: registry.jakepeterson.dev/jpeterson/mini-microservice-blog/ms-posts:latest
      imagePullSecrets:
        - name: privreg
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
  namespace: mms-blog
spec:
  type: ClusterIP
  # Tells the service which label to match with service
  selector:
    app: posts
  ports: 
    - name: posts
      protocol: TCP
      # port service is listening on, could be different
      port: 4000
      # the port that the application is listening on, i.e Express Server listening on 4000
      targetPort: 4000